let mySprite = sprites.create(img`
    . . . . . . . . e e . . . . . . 
    . . . . . e e e e e . . . . . . 
    . . . . . e 3 3 3 . . . . . . . 
    . . . . . . f 3 f . . . . . . . 
    . . . . . . 3 2 3 . . . . . . . 
    . . . . . . . 3 . . . . . . . . 
    . . . . . 5 5 5 5 5 . . . . . . 
    . . . . . 5 5 5 8 5 . . . . . . 
    . . . . . 3 5 5 5 3 . . . . . . 
    . . . . . 3 5 5 5 3 . . . . . . 
    . . . . . . 8 8 8 . . . . . . . 
    . . . . . . 8 . 8 . . . . . . . 
    . . . . . . 8 . 8 . . . . . . . 
    . . . . . . 3 . 3 . . . . . . . 
    . . . . . 4 4 . 4 4 . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
scene.setBackgroundImage(img`
    eeeeeddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddddddddeeeeeddddeeeeeddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddddddddeeeeeddddeeeeeddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddddddddeeeeeddddeeeeeddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddddddddeeeeeddddeeeeeddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddddddddeeeeeddddeeeeeddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeeeeeedddeeeeeddddeeeeeddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeeeeeeddddddddddddeeeeeddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeeeeeeddddddddddddeeeeeddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeeeeeeddddddddddddeeeeeddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeeeeeeddddddddddddeeeeeddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeedddddddddeeeeeeeeeeeeeddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeedddddddddeeeeeeeeeeeeeddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeddeeeeeeeeeeeeeddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeddeeeeeeeeeeeeeddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeddeeeeeeeeeeeeeddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeedddddddddddddddddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeedddddddddddddddddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeddddeeeeeeeeeeeeeeeddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeddddeeeeeeeeeeeeeeeddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeddddeeeeeeeeeeeeeeeddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeddddeeeeeeeeeeeeeeeddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeddddeeeeeeeeeeeeeeeddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeddddeeeeeddddddddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeddddeeeeeddddddddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeddddeeeeeeeeeeeeeeeddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeddddeeeeeeeeeeeeeeeddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeddddeeeeeeeeeeeeeeeddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeddddeeeeeeeeeeeeeeeddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeddddeeeeeeeeeeeeeeeddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddddddddddeeeeedddddddddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddddddddddeeeeedddddddddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeedddeeeeedddddddddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeedddeeeeedddddddddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeedddeeeeedddddddddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeedddeeeeeddeeeeeeeeeeeeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeedddeeeeeddeeeeeeeeeeeeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeedddeeeeeddeeeeeeeeeeeeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeedddeeeeeddeeeeeeeeeeeeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeddddddddddeeeeeeeeeeeeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeedddddddddddddddddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeedddddddddddddddddddddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddeeeee
    eeeeedddddddddddddeeeeeddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddeeeee
    eeeeedddddddddddddeeeeeddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddeeeee
    eeeeedddddddddddddeeeeeddeeeeedddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddeeeee
    eeeeedddddddddddddeeeeeddeeeeedddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeedddddddddddddeeeeeddeeeeedddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeeeedddeeeeeddeeeeedddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeeeedddeeeeeddeeeeedddeeeeeedddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeeeedddeeeeeddeeeeedddeeeeeedddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeeeedddeeeeeddeeeeedddeeeeeedddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeeeedddeeeeeddeeeeedddeeeeeedddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddeeeee
    eeeeedddddeeeeedddeeeeeeeeeeeedddeeeeeedddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddeeeee
    eeeeedddddeeeeedddeeeeeeeeeeeedddeeeeeedddddddddddddddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeedddddeeeeedddeeeeeeeeeeeedddeeeeeedddddddddddddddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeedddddeeeeedddeeeeeeeeeeeedddeeeeeedddddddddddddddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeeeeedeeeeedddeeeeeeeeeeeedddeeeeeedddddddddddddddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeeeeedeeeeedddeeeeeddddddddddeeeeeedddddddddddddddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeeeeedeeeeedddeeeeedeeeeeedddeeeeeedddddddddddddddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeeeeedeeeeedddeeeeeeeeeeeedddeeeeeedddddddddddddddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeeeeedeeeeedddeeeeeeeeeeeedddeeeeeedddddddddddddddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeedddddeeeeedddeeeeeeeeeeeedddeeeeeedddddddddddddddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeedddddeeeeedddeeeeeeeeeeeedddeeeeeedddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddeeeee
    eeeeedddddeeeeedddeeeeeeeeeeeedddeeeeeedddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddeeeee
    eeeeedddddeeeeedddeeeeeddeeeeedddeeeeeedddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddeeeee
    eeeeedddddeeeeedddeeeeeddeeeeedddeeeeeedddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddeeeee
    eeeeedddddeeeeedddeeeeeddeeeeedddeeeeeedddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeeeeeeeeeeedddeeeeeddeeeeedddeeeeeedddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddeeeeeddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeeeeeeeeeeeddddddddddeeeeedddeeeeeedddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddddeeeeeddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeeeeeeeeeeeddddddddddeeeeedddeeeeeedddddddddddddddddddddddddeeeeeddddddddddddddeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeeeeeeeeeeeddddddddddeeeeedddeeeeeedddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeeeeeeeeeeedddeeeeeddeeeeedddeeeeeedddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeedddddddddddddeeeeeddeeeeedddeeeeeedddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeedddddddddddddeeeeeddeeeeedddeeeeeedddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeedddddddddddddeeeeeddeeeeedddeeeeeedddddddddddddddddddddddddeeeeeeeeeeeeeeeeeeeeeeedddddddddddddeeeeeddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeeeeeeeeeeeeddeeeeedddeeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeeeeeeeeeeeeddeeeeedddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeeeeeeeeeeeeddeeeeedddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeeeeeeeeeeeeddeeeeedddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeddeeeeeeeeeeeeeeeeddeeeeedddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeddddddeeeeeddeeeeeddeeeeedddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeddddddeeeeeddeeeeeddeeeeedddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeddddddeeeeeddeeeeeddeeeeedddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeddddddeeeeeddeeeeeddeeeeedddeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeeeeeddeeeeeddeeeeeddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeeeeeddeeeeeddeeeeeddeeeeedddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeeeeeddeeeeeddeeeeeddeeeeeddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeeeeeddeeeeeddeeeeeddeeeeeddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeeeeeddeeeeeddeeeeeddeeeeeddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeddddddeeeeeddeeeeeddeeeeeeeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeeddddddeeeeeddeeeeeddeeeeeeeeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeedddddddddddddddddddddddddddddeeeee
    eeeeedeeeeeeeeeeddeeeeeddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddeeeee
    eeeeedeeeeeeeeeeddeeeeeddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddeeeee
    eeeeedeeeeeeeeeeddeeeeeddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddeeeee
    eeeeedeeeeedddddddeeeeedddddddeeeeeddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddeeeee
    eeeeedeeeeedddddddeeeeedddddddeeeeeddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeedddddddddddddddddddddddddddddeeeee
    eeeeedddddddddddddeeeeedddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeedddddddddddddeeeeeddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    `)
